GET http://localhost:3000/users/
###

POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard12",
  "name": "Adam Richard",
  "password": "richard_5671",
  "gender": "male",
  "location": "Detroit"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "adam_richard12",
  "password": "richard_56712"
}

###

PUT http://localhost:3000/change-password/
Content-Type: application/json

{
  "username": "adam_richard12",
  "oldPassword": "richard_5671",
  "newPassword": "richard_56712"
}

